# Generated by Django 4.1 on 2023-04-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=80)),
                ('is_complete', models.BooleanField(default=False)),
                ('compleated_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_user', models.CharField(max_length=80)),
                ('team', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=80)),
                ('is_complete', models.BooleanField(default=False)),
                ('compleated_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('SubTask', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='Todo.subtask')),
            ],
        ),
    ]
