# Generated by Django 4.1 on 2023-04-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='team',
            field=models.CharField(choices=[('단비', '단비'), ('다래', '다래'), ('블라블라', '블라블라'), ('철로', '철로'), ('땅이', '땅이'), ('해태', '해태'), ('수피', '수피')], max_length=80),
        ),
    ]
