# Generated by Django 4.1 on 2023-04-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_subtask_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='SubTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='Todo.subtask'),
        ),
    ]
