# Generated by Django 4.1 on 2023-04-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_remove_task_subtask_subtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='Task',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Todo.task'),
            preserve_default=False,
        ),
    ]
