# Generated by Django 4.1 on 2023-05-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_alter_subtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subchoic',
            field=models.CharField(blank=True, choices=[('단비', '단비'), ('다래', '다래'), ('블라블라', '블라블라'), ('철로', '철로'), ('땅이', '땅이'), ('해태', '해태'), ('수피', '수피')], max_length=100, null=True),
        ),
    ]
